name: ton-miner-bot

services:
  postgres:
    container_name: "postgres-container"
    build:
      context: ../../
      dockerfile: ./packages/devops/services/db/Dockerfile
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "5434:5432"

  core-miner:
    image: "core-miner:${SERVER_VERSION}"
    container_name: "core-miner-container"
    build:
      context: ../../
      dockerfile: ./packages/devops/services/core-miner/Dockerfile
      args:
        - PROJECT_VERSION=${SERVER_VERSION}
    env_file:
      - services/core-miner/.env
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy

  bot-miner:
    image: "bot-miner:${BOT_VERSION}"
    container_name: "bot-miner-container"
    build:
      context: ../../
      dockerfile: ./packages/devops/services/bot-miner/Dockerfile
      args:
        - PROJECT_VERSION=${BOT_VERSION}
    env_file:
      - ./services/bot-miner/.env
    ports:
      - "5050:5050"
    depends_on:
      - core-miner