name: ton-miner-bot

services:
  postgres:
    container_name: "postgres.prod"
    build:
      context: ../../
      dockerfile: ./packages/devops/services/db/Dockerfile
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "5434:5432"

  server:
    image: "ton_miner_server:${SERVER_VERSION}"
    container_name: "server.prod"
    build:
      context: ../../
      dockerfile: ./packages/devops/services/server/Dockerfile
      args:
        - PROJECT_VERSION=${SERVER_VERSION}
    env_file:
      - ./services/server/.env
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy

  bot:
    image: "ton_miner_bot:${BOT_VERSION}"
    container_name: "bot.prod"
    build:
      context: ../../
      dockerfile: ./packages/devops/services/bot/Dockerfile
      args:
        - PROJECT_VERSION=${BOT_VERSION}
    env_file:
      - ./services/bot/.env
    ports:
      - "5050:5050"
    depends_on:
      - server